const DummySets = {

    UsersData: [
      {
        id: 1,
        image: require('../../assets/images/chief.png'),
        username: 'CryptoChief',
        name: 'Miracle Marcel',
        email: 'Miracle Marcel',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 2,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 3,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 4,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 5,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 6,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 7,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 8,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 9,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 10,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 11,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 12,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 13,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 14,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 15,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 16,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
      {
        id: 17,
        image: require('../../assets/images/blank-dp.png'),
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        phoneNumber: '123-456-7890',
        role: 'User',
        status: 'Active',
      },
    ],
     
    
  }
    
    export default DummySets;
    